"""add model monthly-attendance

Revision ID: 0c05dfd1bcaa
Revises: 3fb6d264ff08
Create Date: 2025-02-17 08:37:30.735998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c05dfd1bcaa'
down_revision = '3fb6d264ff08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attendance_type', sa.Enum('FULL_DAY', 'HALF_DAY', 'ONLINE_DAY', name='attendancetype'), nullable=False),
    sa.Column('is_excused_absence', sa.Boolean(), nullable=True),
    sa.Column('excuse_document', sa.String(length=255), nullable=True),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='unique_employee_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_attendance')
    # ### end Alembic commands ###
