"""Add advancePercentage column to employees

Revision ID: 14a4bc13fce4
Revises: ef94e837778f
Create Date: 2025-02-08 00:18:31.172717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a4bc13fce4'
down_revision = 'ef94e837778f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advancePercentage', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('advancePercentage')

    # ### end Alembic commands ###
